version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: meumysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aluno
      MYSQL_DATABASE: bcd
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno
      MYSQL_ROOT_HOST: '%'
    volumes:
      - meumysql_data:/var/lib/mysql

volumes:
  meumysql_data:
